name: 'Lighthouse CI for Pull Requests'
description: 'Runs Lighthouse CI on a PR and posts the results as a comment'

inputs:
  number:
    description: 'Pull Request number'
    default: ''
  LHCI_GITHUB_TOKEN:
    description: 'LHCI_GITHUB_TOKEN'
    required: true
  GITHUB_TOKEN:
    description: 'GITHUB_TOKEN'
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        sudo apt-get update
        sudo apt-get install -y libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev libasound2
      shell: bash
    - uses: browser-actions/setup-chrome@latest
    - run: |
        chrome --version
        which chrome
      shell: bash
    - name: Audit preview URL with Lighthouse
      id: lhci
      uses: treosh/lighthouse-ci-action@v3
      with:
        configPath: ./.lighthouserc.js
        urls: |
          http://localhost:8000/
          http://localhost:8000/listing
      env:
        LHCI_GITHUB_TOKEN: ${{ inputs.LHCI_GITHUB_TOKEN }}
    - name: Format lighthouse score
      id: format_lhci_score
      uses: actions/github-script@v6
      with:
        github-token: ${{inputs.GITHUB_TOKEN}}
        script: |
          const path = require('path')
          const mapLhciResults = require(path.resolve('./src/mapLhciResults.js'))
          const fromResultsToCommentMapper = require(path.resolve('./src/fromResultsToCommentMapper.js'))
          const results = mapLhciResults(${{ steps.lhci.outputs.manifest }})
          const comment = fromResultsToCommentMapper(results)
          core.setOutput("comment", comment);
    - name: Add comment to PR
      id: comment_to_pr
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        hide_and_recreate: true
        hide_classify: "OUTDATED"
        number: ${{ github.event.issue.number }}
        message: |
          ${{ steps.format_lhci_score.outputs.comment }}