name: Test this action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-skip:
    runs-on: small
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

  test-action:
    runs-on: small
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          number: ${{ github.event.issue.number }}
          LHCI_GITHUB_TOKEN: ${{ secrets.LHCI_GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}